# Generated by Django 3.2.5 on 2022-02-20 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='expires_token',
            new_name='access_token',
        ),
    ]
