# Generated by Django 3.2.5 on 2022-02-20 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_rename_expires_token_spotifytoken_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spotifytoken',
            old_name='expirex_in',
            new_name='expires_in',
        ),
    ]
